
This is a simple Cordapp meant to demonstrate a notarisation issue stemming from
multiple participants being added in series on Corda 4.0.

An IssuingNode is responsible for tracking network assets and participants. It is the sole node
that can issue unique assets or add new participants to an existing asset. The only required signature
to issue assets/add participants to assets is that of the IssuingNode

This notary issue appears during the following workflow.

* A new asset is issued to ClientA.

* ClientB is added as a participant to the asset. (successful)

* ClientC is added as a participant to the asset. (fails)

Example error stacktrace:

```
net.corda.core.flows.NotaryException: Unable to notarise transaction BCD86BEB18E367E9BD67E7E384A180F0A941541F60CF4EF5A107F60EF36151CC : net.corda.core.transactions.SignedTransaction$SignaturesMissingException: Missing signatures on transaction 76D14E for keys: DL7zV8b6UTvmBRSjUWzvxtvoC3eXeK88yd5UW59Ev6me6o, by signers: notary 
	at net.corda.core.internal.notary.NotaryServiceFlow.call(NotaryServiceFlow.kt:73) ~[corda-core-4.0.jar:?]
	at net.corda.core.internal.notary.NotaryServiceFlow.call(NotaryServiceFlow.kt:28) ~[corda-core-4.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:228) ~[corda-node-4.0.jar:?]
	at net.corda.node.services.statemachine.FlowStateMachineImpl.run(FlowStateMachineImpl.kt:45) ~[corda-node-4.0.jar:?]
	at co.paralleluniverse.fibers.Fiber.run1(Fiber.java:1092) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.Fiber.exec(Fiber.java:788) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.doExec(RunnableFiberTask.java:100) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at co.paralleluniverse.fibers.RunnableFiberTask.run(RunnableFiberTask.java:91) ~[quasar-core-0.7.10-jdk8.jar:0.7.10]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
	at net.corda.node.utilities.AffinityExecutor$ServiceAffinityExecutor$1$thread$1.run(AffinityExecutor.kt:63) ~[corda-node-4.0.jar:?]
```

Errors can be generated by running the premade `Run Flow Tests` configuration.